gen_window_test: gen_window.cpp
	g++ -Wall -o gen_window_test gen_window.cpp -I/usr/include/opencv  -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_legacy -lopencv_flann
clean:
	rm -rf gen_window_test
