resize_test: test_resize.cpp
	g++ -o resize_test test_resize.cpp -I/usr/include/opencv  -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_legacy -lopencv_flann
clean:
	rm -rf resize_test;
