sr_one_step_wb_test: sr_one_step_wb.cpp
	g++ -g test_sr_one_step_wb.cpp -o sr_one_step_wb_test -I/usr/include/opencv  -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_legacy -lopencv_flann
clean:
	rm -rf gen_window_test
